//
//  ApiEndUrls.swift
//  Vs_GradItCollege
//
//  Created by Lakshmanan on 04/03/26.
//

struct APIEndpoints {
    
    static let versionCheck = "VersionCheck"
    static let countryList = "Getcountrylist?AppId=1"
    static let ValidateMobileNumber = "ValidateMobileNumber"
    static let forgetpasswordReset = "forgetpasswordReset"
    static let LoginFromApp = "LoginFromApp"
    static let DashboardApi_Live = "DashboardApi_Live"
    static let GetParentUserMenuWithReadWriteAccess = "GetParentUserMenuWithReadWriteAccess"
    static let DeviceToken = "DeviceToken"
    static let GetTextMessageBytype = "GetTextMessageBytype"
    static let GetAddsForCollege = "GetAddsForCollege"
    static let GetStudentWiseAttendanceSummary = "GetStudentWiseAttendanceSummary"
    static let GetLeaveApplicationListForReceiverApp = "GetLeaveApplicationListForReceiverApp"
    static let GetLeaveApplicationListForSenderApp = "GetLeaveApplicationListForSenderApp"
    static let GetLeaveType = "GetLeaveType"
    static let ManageLeaveapplication = "ManageLeaveapplication"
    static let GetOverallcountByMenuType = "GetOverallcountByMenuType"
    static let StudentAskQuestionForApp = "StudentAskQuestionForApp"
    static let GetStudentChatScreenForApp = "GetStudentChatScreenForApp"
    static let GetstaffdetailsForApp = "GetstaffdetailsForApp"
    static let GetStaffClassesforChatForApp = "GetStaffClassesforChatForApp"
    static let GetStaffChatScreenForApp = "GetStaffChatScreenForApp"
    static let AnswerStudentQuestionForApp = "AnswerStudentQuestionForApp"
    static let UnblockStudentForApp = "UnblockStudentForApp"
    static let GetAssignmentListByType = "GetAssignmentListByType"
    static let GetNoticeListByType = "GetNoticeListByType"
    static let GetCircularListByType = "GetCircularListByType"
    static let GetVideoList = "GetVideoList"
    static let GetEventListByType = "GetEventListByType"
    static let Appreadstatus = "Appreadstatus"
    static let GetExamListByType = "GetExamListByType"
    static let GetStudentMarkDetailsForApp = "GetStudentMarkDetailsForApp"
    static let GetSubjectDetailsForSemester = "GetSubjectDetailsForSemester"
    static let getcategorylistforclgeid = "getcategorylistforclgeid"
    static let categorywisestudentcreditdetails = "categorywisestudentcreditdetails"
    static let getsemesterlistforcourseid = "getsemesterlistforcourseid"
    static let semesterwisestudentcreditdetailsALL = "semesterwisestudentcreditdetailsALL"
    static let semesterwisestudentcreditdetails = "semesterwisestudentcreditdetails"
    static let getExamApplicationDetails = "getExamApplicationDetails"
    static let getHallTicketDetails = "getHallTicketDetails"
    static let GetVoiceMessageBytype = "GetVoiceMessageBytype"
    static let GetVoiceMessageHistory = "GetVoiceMessageHistory"
    static let GetTextMessageHistory = "GetTextMessageHistory"
    static let GetDivisions = "GetDivisions"
    static let GetDepartmentsbyDivision = "GetDepartmentsbyDivision"
    static let GetCoursesByDepartment = "GetCoursesByDepartment"
    static let GetSubjectListforparticularstaff = "GetSubjectListforparticularstaff"
    static let GetClassListForTutor = "GetClassListForTutor"
    static let GetGrouplist = "GetGrouplist"
    static let GetstudentListforapp = "GetstudentListforapp"
    static let SendVoiceToParticularTypeFromHistory = "SendVoiceToParticularTypeFromHistory"
    static let SendVoiceToEntireCollegeFromHistory = "SendVoiceToEntireCollegeFromHistory"
    static let SendSMSToEntireCollege = "SendSMSToEntireCollege"
    static let SendSMSToParticularType = "SendSMSToParticularType"
    static let SendSMSToParticularTypeFromTutor = "SendSMSToParticularTypeFromTutor"
    static let GetBranchCollegeList = "GetBranchCollegeList"
    static let ManageNoticeBoard = "ManageNoticeBoard"
    static let ManageNoticeBoardFromTutor = "ManageNoticeBoardFromTutor"
    static let ManageEvents = "ManageEvents"
    static let ManageEventsFromTutor = "ManageEventsFromTutor"
    static let SendVideoToParticularType = "SendVideoToParticularType"
    static let SendVideoToParticularTypeFromTutor = "SendVideoToParticularTypeFromTutor"
    static let ManageAssignmentWithCloudURL = "ManageAssignmentWithCloudURL"
    static let AssignmentDelete = "AssignmentDelete"
    static let SendImageOrPDFToEntireCollegeWithCloudURL = "SendImageOrPDFToEntireCollegeWithCloudURL"
    static let SendImageOrPDFToParticularTypeWithCloudURL = "SendImageOrPDFToParticularTypeWithCloudURL"
    static let SendImageOrPDFToParticularTypeWithCloudURLFromTutor = "SendImageOrPDFToParticularTypeWithCloudURLFromTutor"
    static let SendVideoToEntireCollege = "SendVideoToEntireCollege"
    static let FacultyListForSenderApp = "FacultyListForSenderApp"
    static let ManageLeaveRequest = "ManageLeaveRequest"
    static let GetMentorstudentListforapp = "GetMentorstudentListforapp"
    static let MarkHourWiseAttendance = "MarkHourWiseAttendance"
    static let GetStudentsForHourwiseAttendanceEdit = "GetStudentsForHourwiseAttendanceEdit"
    static let YearAndSectionListforApp = "YearAndSectionListforApp"
    static let GetExamListByTypeforsenderapp = "GetExamListByTypeforsenderapp"
    static let ExamCreation = "ExamCreation"
    static let GetYearListforApp = "GetYearListforApp"
    static let semesterandsectionListforApp = "semesterandsectionListforApp"
    static let getsectionwisesubjectlist = "getsectionwisesubjectlist"
    static let FacultyList = "FacultyList"
    static let EditSectionWiseExamForApp = "EditSectionWiseExamForApp"
    static let GetDetailsForExamEdit = "GetDetailsForExamEdit"
    static let FacultyListforPrincipalLoginSenderApp = "FacultyListforPrincipalLoginSenderApp"
    static let AddeventphotosWithCloudURL = "AddeventphotosWithCloudURL"
    static let ViewAssignmentContent = "ViewAssignmentContent"
    static let GetAssignmentSubmissions = "GetAssignmentSubmissions"
    static let AddMarksForAssignment = "AddMarksForAssignment"
    static let GetVideoContentRestriction = "GetVideoContentRestriction"
    static let GetStudentWiseAttendanceDetails = "GetStudentWiseAttendanceDetails"
    static let SubmitAssignmentFromAppWithCloudURL = "SubmitAssignmentFromAppWithCloudURL"
    static let GetProfileDetails = "GetProfileDetails"
    static let GetNotificationForCollege = "GetNotificationForCollege"
    static let changepassword = "changepassword"
    static let forgetpassword = "forgetpassword"
    static let VerifyOTP = "VerifyOTP"
    static let GetAttendanceClassListForStaff = "GetAttendanceClassListForStaff"
    static let profile_get_profile = "profile/get-profile/"
    static let academicrecord_get_academic = "academicrecord/get-academic/"
    static let skillset_get_skillset = "skillset/get-skillset/"
    static let profile_add_edit_profile = "profile/add-edit-profile"
    static let academicrecord_add_edit_academic = "academicrecord/add-edit-academic"
    static let skillset_get_softskill = "skillset/get-softskill"
    static let skillset_add_edit_skillset = "skillset/add-edit-skillset"
    static let get_resumetemplatethemecolor = "get/resumetemplatethemecolor"
    static let resume_post_resume = "resume/post-resume"
    static let resume_saveTitleResume = "resume/saveTitleResume"
    static let get_profileresume = "get/profileresume"
    static let get_uploadresume = "get/uploadresume"
    static let UpdateBiometricLocation = "UpdateBiometricLocation"
    static let GetBiometricPunchHistory = "GetBiometricPunchHistory"
    
    
    
    static let placementEvent = "students/student-placement-events"
    static let placementEventHistorical = "students/student-placement-events-historical"
    static let trainingEvent = "students/student-career"
    static let trainingEventHistorical = "students/student-career-historical"
    static let GetStaffLocationDetails = "GetStaffLocationDetails"
    static let SetBiometricLocation = "SetBiometricLocation"
    static let BiometricEntryusingApp = "BiometricEntryusingApp"
    static let GetBiometricPrincipalAttendance = "GetBiometricPrincipalAttendance"
    static let RemoveBiometricLocation = "RemoveBiometricLocation"
    static let GetBiometricLocationHistory = "GetBiometricLocationHistory"
    static let GetStaffListforBiometric = "GetStaffListforBiometric"

}
